# Generated by Django 3.2.12 on 2022-03-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_design_dec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='dec',
            new_name='image',
        ),
    ]
